<nav class="navbar">
    <div class="navbar-container">
        <a id="org-logo" href="/ABCOrganization"><img src="/resources/images/logo.png" class="navbar-logo"></a>
        <div class="navbar-links" id="nav-bar">
            <a href="/ABCOrganization" class="navbar-link" id="org-home"> Home</a>
            <a href="/ABCOrganization/apis" class="navbar-link" id="org-apis"> APIs</a>
        </div>
    </div>
</nav>

<header class="header">
    <div class="org-container">
        <h1 class="header-title">Welcome to ABC Organization</h1>
    </div>
</header>
<main class="main-content">
    <div class="org-container">
        <section class="description-section">
            <h2 class="description-title">About Us</h2>
            <p class="description-text">
                Our organization is dedicated to making the world a better place. We focus on community development, 
                educational programs, and sustainable living initiatives. Join us in our mission to create a positive impact 
                in the lives of individuals and communities around the globe. Since our founding, we have worked tirelessly to support various causes. Our efforts have included building 
                schools in underserved areas, providing scholarships to talented students, and organizing community events 
                to raise awareness about environmental conservation. We believe that through collaboration and dedication, 
                we can create lasting change.
            </p>
        </section>
        <section class="image-section">
            <img src="/resources/images/org-landing-page.jpeg" alt="Our Organization" class="organization-image">
        </section>
    </div>
</main>
<footer>
    &copy; 2023 XYZ Organization. All rights reserved.
</footer>